glotzerlab/signac-docs

docs/source/recipes.rst

This is certainly not the only way, but I think this is a useful recipe
that should be in every user's toolbox.

Add recipe on how to implement parameter-dependent operations.

---

docs/source/acknowledge.rst

And a few other minor updates.

Update the acknowledgments page with the latest Zenodo DOI.

---

docs/source/tutorial.rst

These examples address Issue #11 with realistic output from running the ideal gas tutorial project on Stampede2 and by linking to relevant documentation sections on cluster submission and environment management.

Cluster submission examples

---

docs/source/dashboard.rst

Preview: https://docs.signac.io/en/update-dashboard-guide/

Updated dashboard topic guide.

---

docs/source/query.rst

This is long overdue, sorry this issue got lost.

Fix some spacing, add documentation of not operator. Resolves #10

---

docs/source/templates.rst

Associated with glotzerlab/signac-flow#118.

Add documentation of callable directives

---

docs/source/tutorial.rst

Add tip about signac shell.

---

docs/source/index.rst
docs/source/intro.rst

I followed HOOMD-blue's example and also added a link to Github.

Restructure nav bar and add GitHub.

---

docs/source/tutorial.rst

Replace os.path.isfile with job.isfile
See issue: #43

Fix volume_computed

---

docs/source/environments.rst

Documentation corresponding to glotzerlab/signac-flow#124.

Documentation for opting out of environments or manually setting an environment

---

docs/source/recipes.rst

Add introduction and simple examples of replica index into recipes.rst flie.

add introduction and simple examples of replica index into recipes.rst

---

docs/source/tutorial.rst

Tutorial correction

---

docs/source/flow-project.rst

Missing ':' on line 63
Prevents SyntaxError for new / first-time users on docs:
https://docs.signac.io/en/latest/flow-project.html
-[✔]  I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-docs/blob/master/CONTRIBUTING.md).
-[✔] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-docs/blob/master/ContributorAgreement.md).
-[✔] My code follows the [code style guideline](https://github.com/glotzerlab/signac-docs/blob/master/CONTRIBUTING.md#code-style) of this project.
If necessary:
-[   ] I have updated the API documentation as part of the package doc-strings.
-[   ] I have created a separate pull request to update the framework documentation on signac-docs and linked it here.
-[   ] I have updated the …

Fixed minor SyntaxError in docs

---

docs/source/flow-group.rst
docs/source/recipes.rst
docs/source/reference.rst
docs/source/tutorial.rst

Added documentation about the `FlowGroup` class to our general docs.
Updates the documentation to be current with `signac-flow`.

Flowgroup documentation

---

docs/source/flow-project.rst

The use of the configuration value `status_parallelization` is explained via this update in documentation.
fixes #86

Documentation update for parallelized status fetching

---

docs/source/community.rst
docs/source/installation.rst

Follows changes proposed in https://github.com/glotzerlab/signac-website/pull/25
De-duplicating content between website and documentation.

Update docs with content from website refactor

---

docs/source/flow-group.rst

See https://github.com/glotzerlab/signac-flow/pull/297. This remove docs about running groups in parallel.

Remove docs about running groups in parallel.

---

docs/source/community.rst

Added user guide to set up a pre-commit hook using [pre-commit](https://pre-commit.com/)
Should be merged after [signac/#358](https://github.com/glotzerlab/signac/pull/358) gets merged

Add docs for pre-commit

---

docs/source/recipes.rst

Following a Slack conversation with Miguel, I decided to add this recipe to help users who want to perform "grid initialization" without using many nested for loops.
This is a commonly requested user need. I have seen many signac users with similar snippets stored somewhere for this purpose -- we might as well make one snippet canonical-ish and publicly usable.

Add recipe for grid initialization.

---

docs/source/recipes.rst

This is a small change but I'm hoping it'll make the sidebar smaller and more legible. I just shortened the subheadings for clarity and changed the instances of "statepoint" to "state point" for consistency.

Cleanup How-To Subheadings

---

docs/source/installation.rst
docs/source/packages.rst

This pull request updates the docs to provide an explanation to the users of why they should install the packages in the signac framework.
Resolves #96

Update the installation guide

---

docs/source/tutorial.rst

While completing the tutorial, an error to say volume not defined was thrown. Keeping the volume group name consistent removes the error.
Allows tutorial code to be run without errors

Make volume group name consistent

---

docs/source/cluster_submission.rst
docs/source/environments.rst
docs/source/templates.rst

Related to https://github.com/glotzerlab/signac-flow/pull/491
The PR to signac-flow should be merged first!
Resolves https://github.com/glotzerlab/signac-flow/issues/388

Change Torque to PBS.

---

docs/source/cluster_submission.rst
docs/source/environments.rst

See this issue https://github.com/glotzerlab/signac-flow/issues/355

Added warnings for chaging job names

---

docs/source/community.rst

Point users to Slack for support. We don't actively monitor Gitter as much.

Point users to Slack for support.

---

.readthedocs.yaml
docs/requirements.txt

- Add .readthedocs.yaml.
- Require sphinx_rtd_theme>=0.5.2.
Fixes some issues with CSS. See https://github.com/readthedocs/sphinx_rtd_theme/issues/1115
I will merge once I verify that the issue is fixed.

Fix CSS issues on ReadTheDocs.

---

.readthedocs.yaml
docs/requirements.txt

Some minor maintenance for ReadTheDocs.

Update ReadTheDocs config files.

---

docs/source/dashboard.rst

**[View the build here
](https://signac--165.org.readthedocs.build/en/165/dashboard.html)**
Provides examples in light of https://github.com/glotzerlab/signac-dashboard/pull/110

Document project overview page

---

docs/source/tips_and_tricks.rst

Adds notes on scaling up signac projects from discussion with @rskye144.

Add notes on performance

---

docs/source/dashboard.rst

Document the dashboard login token and provide users guidance on using it.
Merge this after the next `signac-dashboard` release.
https://github.com/glotzerlab/signac-dashboard/pull/158 changes the steps needed to connect to a dashboard. Explain that process to users in the dashboard quick start documentation.

Document the dashboard token login.

---

docs/source/aggregation.rst
docs/source/flow-project.rst
docs/source/hooks.rst
docs/source/recipes.rst
docs/source/tutorial.rst

- fix: Update condition decorator positions for 0.23.0
- fix: Use opeation's aggregator keyword argument over decorator
- Add comments about required decorator ordering.
Updates documentation to flow 0.23.0 requirements any 0.24.0 removals.
Keeps our documentation up to date.

Update flow syntax to 0.23.0

---

docs/source/dashboard.rst

https://github.com/glotzerlab/signac-dashboard/pull/153
I tested it by building locally

Dashboard for signac 1.8

---

.pre-commit-config.yaml
docs/source/cluster_submission.rst
docs/source/flow-group.rst
docs/source/recipes.rst

Update doc's `flow` syntax.
- Remove @flow.cmd
- Remove @FlowProject.operation.with_directives
- Remove @FlowGroup.with_directives
To have correct syntax.

fix: Update flow syntax.

---

docs/source/recipes.rst

Fix MPI command line recipe.

---

docs/source/flow-project.rst
docs/source/query.rst
docs/source/recipes.rst
docs/source/templates.rst

I did a pass for common fixes going to signac 2.
In addition, query arguments passed in JSON must be lowercase, so I fixed this in the documentation.
Resolves: #192

Fixes for signac 2
