glotzerlab/signac-docs

- docs/source/examples.rst
There is no link to the examples repository on the examples page.
> Add link to examples repository.

- docs/source/environments.rst
They are loaded by default as of flow 0.8.
> Remove tip about packaged environments

- docs/source/installation.rst
All packages in the framework now require Python 3.5+ after https://github.com/glotzerlab/signac/pull/232 is merged. **Reviewers: please merge once approved.**
> Updated supported versions.

- examples/hoomd-lj/src/init.py
- examples/hoomd-lj/src/project.py
This fixes issue #51 
Really the only issue with the tutorial was calling this an ideal gas project when really it is comparing an LJ fluid to an ideal gas.
> set project name to reflect name of the tutorial

- docs/source/recipes.rst
The recipe shows how to use the post.never condition to enforce eligibility for the execution for a specific operation for debugging purposes.
> Add recipe for the use of the post.never condition.

- .github/ISSUE_TEMPLATE/documentation.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- ContributorAgreement.md
- LICENSE.txt
This repository was missing a license and contributing agreement. I also added templates for issues and pull requests. These are modified slightly from the files in signac and signac-flow repositories to account for the fact that this is mostly documentation. We also don't track contributors or changelogs in this repository -- I don't think that is needed, so I removed the corresponding sections of those documents.
> Add LICENSE.

- docs/source/tutorial.rst
The documented output from signac schema for the ideal gas tutorial gives the incorrect pressure range 0 to 10. From the init script, the result is 0 to 9 and the change correctly shows that.
Changed the beginning of the tutorial documentation to correctly reflect the output of signac schema. 
Fixes issue: https://github.com/glotzerlab/signac-docs/issues/72
> Edited tutorial documentation

- docs/source/quickstart.rst
- docs/source/tutorial.rst
explicitly stating where signac-flow is introduced when it is used in tutorials
addressing #83
> adding flow more explicitly to quickstart and tutorial

- docs/source/conf.py
Small fix to improve navigability of the docs while large scale projects like #64 continue.
I always felt lost in the docs, particularly by not knowing the hierarchy of items in the sidebar.
With these settings:
- show a plus sign when mousing over headings in the sidebar to avoid having to click to load the page to expand the subtree
- show navigation buttons at top and bottom of page because lots of our pages are long
The options are described [here](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html).
**Before**
**After**
> Simple sphinx settings to improve navigation

- docs/source/community.rst
Adds embedded Google Calendar to the documentation's Community page.
I'm not sure if this is the best place for this information, but it's next to other info about public support channels. Other suggestions welcome.
Note for reviewers, please check if the time zone in the rendered calendar matches your local time zone. In my understanding, the the embedding link uses my time zone by default (Central) but I think I fixed it to match the viewer's time zone.
Helps make meetings more accessible to the community.
> Add Google Calendar to docs.

- docs/source/conf.py
- docs/source/jobs.rst
- docs/source/projects.rst
Accessing the project-level `data` attribute from multiple processes at the same time can give errors. After [being advised in the slack support channel](https://signac.slack.com/archives/CVC04S9TN/p1606922468155000) I thought it would be nice to mention this in the documentation.
Added a paragraph about how to circumvent this limitation, both in the multiple-readers case or the single-writer-multiple-readers case. I included links to the [`h5py` SWMR docs](https://docs.h5py.org/en/stable/swmr.html), the [`multiprocessing` synchronization primitives docs](https://docs.python.org/3/library/multiprocessing.html#synchronization-between-processes) and the [`posix_ipc` semaphores docs](http://semanchuk.com/philip/posix_ipc/#semaphore).
Hopefully the next person to come across this problem can …
> Added warning about concurrent access to project-level data

- docs/source/community.rst
`requirements-precommit.txt` is now in the `requirements` folder.
I've updated the tip on our docs page.
We should keep it easy to contribute to the package :+1:
> Update docs with new requirements layout

- docs/source/acknowledge.rst
I added our SciPy 2018 paper as an additional publication. I find myself wanting the citation for that paper somewhat often and thought it would be good to add to our docs. I put it in a separate section so that it is not confused with our "preferred citation."
> Add SciPy 2018 paper as an additional publication

- docs/source/query.rst
Add documentation for query filters that combine state point and document keys.
Accompanies glotzerlab/signac#332
> Add documentation of query namespaces.

- docs/source/tutorial.rst
Added missing .py suffix to ``$ python project run``
> Corrected typo in "Extending the workflow"

- docs/source/cluster_submission.rst
- docs/source/flow-group.rst
- docs/source/recipes.rst
This changes the documentation to use the `FlowProject.operation.with_directives` decorator over `flow.directives`. This is to teach a more coherent syntax with `FlowGroupEntry.with_directives`.
Is the corresponding documentation PR for https://github.com/glotzerlab/signac-flow/pull/502.
> Update documentation to use new operation.with_directives decorator

- docs/source/cluster_submission.rst
Attempting to fix issue (we fail on warnings):
```
/home/docs/checkouts/readthedocs.org/user_builds/signac/checkouts/latest/docs/source/cluster_submission.rst:5: WARNING: Duplicate explicit target name: "directives".
```
https://readthedocs.org/projects/signac/builds/14007143/
Merging if docs build successfully.
> Make reference name more specific to avoid conflicts.

- .pre-commit-config.yaml
- docs/source/acknowledge.bib
- docs/source/acknowledge.rst
- docs/source/conf.py
- docs/source/signac.bib
Adds new citation information for the SciPy 2021 proceedings paper (no DOI is available yet). For now, I recommend citing the new SciPy paper only in cases where the content specifically references the new features that have been recently added:
> If your paper makes use of the signac-flow features for aggregation, groups, and bundling or signac features for synced collections, consider citing:
I reorganized citation information to use BibTeX files that match the format of the "Scientific Papers" page.
I made the recommended citation statement shorter, since I have seen several users (including myself) adapt the statement in this way.
Lastly, I edited some bibtex-tidy pre-commit settings to wrap content at 90 characters. That's what fits on screen (on a desktop or laptop) without creating …
> Update citation information.

- docs/source/tutorial.rst
Added `import json`  in **Grouping Operations** documentation
1. `json` is being used in the code sample but was not imported.
2.  Changed `store_volume_in_document` to `store_volume_in_json_file` in the grouping documentation, because the function used in the following code sample is `store_volume_in_json_file`
> Updated Grouping Operations Documentation

- .pre-commit-config.yaml
- docs/source/aggregation.rst
- docs/source/cluster_submission.rst
- docs/source/collections.rst
- docs/source/configuration.rst
- docs/source/dashboard.rst
- docs/source/environments.rst
- docs/source/flow-group.rst
- docs/source/flow-project.rst
- docs/source/hooks.rst
- docs/source/jobs.rst
- docs/source/projects.rst
- docs/source/query.rst
- docs/source/quickstart.rst
- docs/source/recipes.rst
- docs/source/tips_and_tricks.rst
- docs/source/tutorial.rst
This PR adds a pre-commit hook for [blacken-docs](https://github.com/asottile/blacken-docs).
I like the idea of enforcing code style in our documentation, especially because long lines render poorly in the online documentation. The line wrapping enforced by `black` will prevent such long lines that would create a scrollbar in the code snippet.
> Blacken docs.

- docs/source/conf.py
Sphinx 5 throws a warning, causing ReadTheDocs builds to fail:
```
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
```
This PR fixes that warning/error. I will merge once CI passes.
> Use language = "en" for compatibility with Sphinx 5.

- docs/source/conf.py
- docs/source/recipes.rst
Adds a how-to on debugging operations that are run within a container or a different environment than the operation is submitted or run on.
This is actually somewhat difficult to solve. I had added a `post_command` directive on local `signac-flow` branches to achieve this, but it is possible to do without having to modify `flow` hence the PR.
> Add how to on debugging containered operations.

- docs/source/flow-project.rst
Updates the syntax for specifying `with_job` and `cmd` in flow.
glotzerlab/signac-flow/pull/679.
> Update syntax for with_job and cmd options.

- docs/source/cluster_submission.rst
Users often want to use the `submit --bundle --parallel` flag on GPU clusters, but this doesn't work. Update documentation so users know its limits.
I explain bundling first without the `--parallel` flag.
I moved the explanation of `--parallel` to the end and introduced it specifically for CPU nodes.
Added a warning for GPU nodes. We should link to the aggregation tutorial eventually.
See for example #27 or discussion at [glotzerlab/signac#593
](https://github.com/glotzerlab/signac-flow/pull/594)
> Clarify limits of submit --bundle --parallel

- CONTRIBUTING.md
- docs/source/community.rst
- docs/source/installation.rst
Fixes outdated references to setup.py in the docs.
Aligns with https://github.com/glotzerlab/signac/pull/878, https://github.com/glotzerlab/signac-flow/pull/704.
> Migrate setup.py references to pyproject.toml.

- docs/source/acknowledge.bib
- docs/source/acknowledge.rst
Companion PR to https://github.com/glotzerlab/signac/pull/903. We haven't been keeping Zenodo up to date (last updated February 2019) and it gets very few citations (only 4 citations listed on the [Zenodo page](https://zenodo.org/record/2581327) and 9 on [Google Scholar](https://scholar.google.com/scholar?cites=16862461478172395566&as_sdt=400005&sciodt=0,14&hl=en), compared to [95 Google Scholar citations of the 2018 paper](https://scholar.google.com/scholar?cites=14270565839129827405&as_sdt=400005&sciodt=0,14&hl=en)). We're going to remove it, to simplify the process of acknowledgement and avoid pointing to outdated content.
> Remove Zenodo reference.

- docs/source/environments.rst
- docs/source/templates.rst
To avoid warnings when adding/using environments.
Added some text in the documentation on how to add environments without getting warnings. 
- [ x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-docs/blob/main/CONTRIBUTING.md).
- [x ] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-docs/blob/main/ContributorAgreement.md).
- [x ] My code follows the [code style guideline](https://github.com/glotzerlab/signac-docs/blob/main/CONTRIBUTING.md#code-style) of this project.
> Add note about defining custom environments in a separate module

- .readthedocs.yaml
ReadTheDocs shared the following announcement:
> We are announcing the deprecation of projects using Sphinx or MkDocs without an explicit configuration in their `.readthedocs.yaml` file. After January 20, 2025, Read the Docs will require explicit configuration for all Sphinx and MkDocs projects.
This adds the explicit key required by the above.
> Add explicit ReadTheDocs configuration.
